Use correct extension for library source file
The previous file extension .ccp causes the source file to not be compiled, resulting in the error when compiling:

C:\Users\per\AppData\Local\Temp\ccPwZlTq.ltrans0.ltrans.o: In function `__static_initialization_and_destruction_0':

E:\electronics\arduino\libraries\HC-SR04-master\examples\ultrasonic/ultrasonic.ino:6: undefined reference to `Ultrasonic::Ultrasonic(unsigned char, unsigned char)'

C:\Users\per\AppData\Local\Temp\ccPwZlTq.ltrans0.ltrans.o: In function `loop':

E:\electronics\arduino\libraries\HC-SR04-master\examples\ultrasonic/ultrasonic.ino:22: undefined reference to `Ultrasonic::measure()'

E:\electronics\arduino\libraries\HC-SR04-master\examples\ultrasonic/ultrasonic.ino:26: undefined reference to `Ultrasonic::get_cm()'